In [12]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Glass.csv')

In [3]:
df

S.no       Rl     Na    Mg    AL     Si     K    Ca    Ba   Fe  Type
0       1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1       2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2       3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3       4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4       5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..    ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209   210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210   211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211   212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212   213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213   214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 11 columns]

In [4]:
df.describe()

S.no          Rl          Na          Mg          AL          Si  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean   107.500000    1.518365   13.407850    2.684533    1.444907   72.650935   
std     61.920648    0.003037    0.816604    1.442408    0.499270    0.774546   
min      1.000000    1.511150   10.730000    0.000000    0.290000   69.810000   
25%     54.250000    1.516522   12.907500    2.115000    1.190000   72.280000   
50%    107.500000    1.517680   13.300000    3.480000    1.360000   72.790000   
75%    160.750000    1.519157   13.825000    3.600000    1.630000   73.087500   
max    214.000000    1.533930   17.380000    4.490000    3.500000   75.410000   

                K          Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  214.000000  
mean     0.497056    8.956963    0.175047    0.057009    2.780374  
std      0.652192    1.423153    0.497219    0.097439    2.103739  
min      0.000000    5.430000    0.000000    0.000000    1.000000  
25%      0.122500    8.240000    0.000000    0.000000    1.000000  
50%      0.555000    8.600000    0.000000    0.000000    2.000000  
75%      0.610000    9.172500    0.000000    0.100000    3.000000  
max      6.210000   16.190000    3.150000    0.510000    7.000000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   S.no    214 non-null    int64  
 1   Rl      214 non-null    float64
 2   Na      214 non-null    float64
 3   Mg      214 non-null    float64
 4   AL      214 non-null    float64
 5   Si      214 non-null    float64
 6   K       214 non-null    float64
 7   Ca      214 non-null    float64
 8   Ba      214 non-null    float64
 9   Fe      214 non-null    float64
 10  Type    214 non-null    int64  
dtypes: float64(9), int64(2)
memory usage: 18.5 KB


In [40]:
Y=df['Type']
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: Type, dtype: int64

In [29]:
Y=df.drop("Type",axis=1)
df.head()

S.no       Rl     Na    Mg    AL     Si     K    Ca   Ba   Fe  Type
0     1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1     2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2     3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3     4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4     5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [48]:
from sklearn import preprocessing
x = df.values

min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df=pd.DataFrame(x_scaled)
df.head()

0         1         2         3         4         5         6   \
0  0.000000  0.432836  0.437594  1.000000  0.252336  0.351786  0.009662   
1  0.004695  0.283582  0.475188  0.801782  0.333333  0.521429  0.077295   
2  0.009390  0.220808  0.421053  0.790646  0.389408  0.567857  0.062802   
3  0.014085  0.285777  0.372932  0.821826  0.311526  0.500000  0.091787   
4  0.018779  0.275241  0.381955  0.806236  0.295950  0.583929  0.088567   

         7    8    9    10  
0  0.308550  0.0  0.0  0.0  
1  0.223048  0.0  0.0  0.0  
2  0.218401  0.0  0.0  0.0  
3  0.259294  0.0  0.0  0.0  
4  0.245353  0.0  0.0  0.0

In [50]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df,Y, test_size=0.30, random_state=42)
print((X_train.shape))

(149, 11)


In [51]:
print((y_train.shape))

(149,)


In [52]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
clf=DecisionTreeClassifier(criterion="entropy")
clf=clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
accuracy_score(y_test,y_pred)

1.0

In [55]:
df.mean()
df

0         1         2         3         4         5         6   \
0    0.000000  0.432836  0.437594  1.000000  0.252336  0.351786  0.009662   
1    0.004695  0.283582  0.475188  0.801782  0.333333  0.521429  0.077295   
2    0.009390  0.220808  0.421053  0.790646  0.389408  0.567857  0.062802   
3    0.014085  0.285777  0.372932  0.821826  0.311526  0.500000  0.091787   
4    0.018779  0.275241  0.381955  0.806236  0.295950  0.583929  0.088567   
..        ...       ...       ...       ...       ...       ...       ...   
209  0.981221  0.223003  0.512782  0.000000  0.806854  0.500000  0.012882   
210  0.985915  0.250219  0.630075  0.000000  0.529595  0.580357  0.000000   
211  0.990610  0.417032  0.545865  0.000000  0.538941  0.644643  0.000000   
212  0.995305  0.235294  0.548872  0.000000  0.514019  0.678571  0.000000   
213  1.000000  0.261633  0.526316  0.000000  0.557632  0.633929  0.000000   

           7         8    9    10  
0    0.308550  0.000000  0.0  0.0  
1    0.223048  0.000000  0.0  0.0  
2    0.218401  0.000000  0.0  0.0  
3    0.259294  0.000000  0.0  0.0  
4    0.245353  0.000000  0.0  0.0  
..        ...       ...  ...  ...  
209  0.348513  0.336508  0.0  1.0  
210  0.276022  0.504762  0.0  1.0  
211  0.279740  0.520635  0.0  1.0  
212  0.283457  0.498413  0.0  1.0  
213  0.296468  0.530159  0.0  1.0  

[214 rows x 11 columns]

In [57]:
from sklearn.datasets import load_digits
from sklearn.linear_model import Perceptron
clf=Perceptron(tol=3, random_state=0)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.8

In [58]:
from sklearn.neural_network import MLPClassifier
Classifier=MLPClassifier(solver='lbfgs',alpha=5,hidden_layer_sizes=(5,2), random_state=1)
Classifier.fit(X_train,y_train)

MLPClassifier(alpha=5, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [60]:
y_pred= Classifier.predict(X_test)

In [61]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 0 19  0  0  0  0]
 [ 0 23  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0 10  0  0  0  0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        19
           2       0.35      1.00      0.52        23
           3       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00        10

    accuracy                           0.35        65
   macro avg       0.06      0.17      0.09        65
weighted avg       0.13      0.35      0.18        65



C:\Users\SHIVAM\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SHIVAM\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SHIVAM\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0),solver='lbfgs',multi_class='multinomial'.fit(X_train , y_train)

In [70]:
clf.score(X_test,y_test)

0.8